# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
      day: "monday"
    labels:
      - "dependencies"
      - "bot"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    auto-merge: true
    assignees:
      - "ibreakthecloud"
